/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fuel.rewards.transaction.service;


import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class RewardsServiceApplication {
    public static void main(String[] args) throws Exception {
        SpringApplication.run(RewardsServiceApplication.class, args);
    }
}
