/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fuel.rewards.transaction.service;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        RewardsServiceApplication classUnderTest = new RewardsServiceApplication();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
